# Generated by Django 5.2.14 on 2026-05-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensorreading_anomaly_score_sensorreading_is_anomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='health_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
