# Generated by Django 5.2.14 on 2026-05-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sensorreading_health_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='predicted_ttf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
