services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: phm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1407

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: